<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class GSM_Slider_Templates {

	/**
	 * Singleton instance.
	 *
	 * @var GSM_Slider_Templates|null
	 */
	private static $instance = null;

	/**
	 * Get singleton instance.
	 *
	 * @return GSM_Slider_Templates
	 */
	public static function get_instance() {
		if ( null === self::$instance ) {
			self::$instance = new self();
		}
		return self::$instance;
	}

	/**
	 * Constructor.
	 */
	private function __construct() {
		add_action( 'wp_ajax_gsm_get_templates', array( $this, 'ajax_get_templates' ) );
		add_action( 'wp_ajax_gsm_get_template', array( $this, 'ajax_get_template' ) );
	}

	/**
	 * Discard accidental output so admin-ajax stays valid JSON (notices from other code).
	 *
	 * @param mixed $data Payload for wp_send_json_success().
	 */
	private function send_json_success_clean( $data ) {
		if ( ob_get_length() ) {
			ob_clean();
		}
		wp_send_json_success( $data );
	}

	/**
	 * @param mixed $data Optional error payload.
	 */
	private function send_json_error_clean( $data = null ) {
		if ( ob_get_length() ) {
			ob_clean();
		}
		wp_send_json_error( $data );
	}

	/**
	 * AJAX: Return list of available templates (metadata only).
	 */
	public function ajax_get_templates() {
		check_ajax_referer( 'gsm_templates_nonce', 'nonce' );
		if ( ! current_user_can( 'edit_posts' ) ) {
			wp_die( -1 );
		}

		$templates = $this->get_templates();
		$list      = array();

		foreach ( $templates as $id => $tpl ) {
			$list[] = array(
				'id'          => $id,
				'title'       => $tpl['title'],
				'description' => $tpl['description'],
				'category'    => $tpl['category'],
				'thumbnail'   => $tpl['thumbnail'],
			);
		}

		$this->send_json_success_clean( $list );
	}

	/**
	 * AJAX: Return full settings for a specific template.
	 */
	public function ajax_get_template() {
		check_ajax_referer( 'gsm_templates_nonce', 'nonce' );
		if ( ! current_user_can( 'edit_posts' ) ) {
			wp_die( -1 );
		}

		$template_id = isset( $_POST['template_id'] ) ? sanitize_key( wp_unslash( $_POST['template_id'] ) ) : '';
		$templates   = $this->get_templates();

		if ( ! isset( $templates[ $template_id ] ) ) {
			$this->send_json_error_clean( array( 'message' => 'Template not found.' ) );
		}

		$this->send_json_success_clean( $templates[ $template_id ]['settings'] );
	}

	/**
	 * All built-in templates.
	 *
	 * @return array
	 */
	public function get_templates() {
		return array(

			'hero-dark' => array(
				'title'       => 'Hero Dark',
				'description' => 'Full-screen dark hero with cinematic effect',
				'category'    => 'hero',
				'thumbnail'   => 'https://picsum.photos/seed/hero-dark/400/225',
				'settings'    => array(
					'content_source'        => 'custom',
					'effect'                => 'fade',
					'autoplay'              => 'yes',
					'delay'                 => 6000,
					'speed'                 => 1000,
					'loop'                  => 'yes',
					'arrows'                => 'yes',
					'pagination_type'       => 'bullets',
					'slider_height'         => array( 'size' => 100, 'unit' => 'vh' ),
					'content_bg'            => 'rgba(0,0,0,0)',
					'content_glass_effect'  => '',
					'content_alignment'     => 'left',
					'heading_color'         => '#ffffff',
					'text_color'            => 'rgba(255,255,255,0.85)',
					'btn_bg'                => '#ffffff',
					'btn_color'             => '#111111',
					'btn_bg_hover'          => '#f0f0f0',
					'btn_border_radius'     => array( 'size' => 4 ),
					'slides_data'           => array(
						array(
							'media_type'            => 'image',
							'bg_image'              => array( 'url' => 'https://picsum.photos/seed/dark1/1920/1080' ),
							'image_fit'             => 'cover',
							'image_position'        => 'center center',
							'image_effect'          => 'zoom',
							'overlay_type'          => 'gradient',
							'overlay_gradient_start'=> 'rgba(0,0,0,0.75)',
							'overlay_gradient_end'  => 'rgba(0,0,0,0.15)',
							'overlay_gradient_direction' => 'to top',
							'heading'               => 'Elevate Your Vision',
							'heading_tag'           => 'h1',
							'description'           => 'Create stunning experiences that captivate your audience and drive results.',
							'animation'             => 'fade-up',
							'btn_text'              => 'Get Started',
							'btn_url'               => array( 'url' => '#' ),
							'content_align'         => 'left',
							'content_vertical'      => 'middle',
							'content_box_enable'    => 'yes',
							'content_max_width'     => array( 'size' => 580, 'unit' => 'px' ),
							'cinematic_effect'      => 'yes',
						),
						array(
							'media_type'            => 'image',
							'bg_image'              => array( 'url' => 'https://picsum.photos/seed/dark2/1920/1080' ),
							'image_fit'             => 'cover',
							'image_position'        => 'center center',
							'image_effect'          => 'parallax',
							'overlay_type'          => 'gradient',
							'overlay_gradient_start'=> 'rgba(0,0,0,0.7)',
							'overlay_gradient_end'  => 'rgba(0,0,0,0.1)',
							'overlay_gradient_direction' => 'to top',
							'heading'               => 'Build Something Great',
							'heading_tag'           => 'h1',
							'description'           => 'Powerful tools designed for modern creators and forward-thinking teams.',
							'animation'             => 'fade-left',
							'btn_text'              => 'Learn More',
							'btn_url'               => array( 'url' => '#' ),
							'content_align'         => 'left',
							'content_vertical'      => 'middle',
							'content_box_enable'    => 'yes',
							'content_max_width'     => array( 'size' => 580, 'unit' => 'px' ),
							'cinematic_effect'      => 'yes',
						),
						array(
							'media_type'            => 'image',
							'bg_image'              => array( 'url' => 'https://picsum.photos/seed/dark3/1920/1080' ),
							'image_fit'             => 'cover',
							'image_position'        => 'center center',
							'image_effect'          => 'zoom',
							'overlay_type'          => 'solid',
							'overlay_color'         => 'rgba(10,10,30,0.65)',
							'heading'               => 'Make Your Mark',
							'heading_tag'           => 'h1',
							'description'           => 'Join thousands of creators who trust our platform to bring their ideas to life.',
							'animation'             => 'zoom-in',
							'btn_text'              => 'Start Free',
							'btn_url'               => array( 'url' => '#' ),
							'content_align'         => 'center',
							'content_vertical'      => 'middle',
							'content_box_enable'    => 'yes',
							'content_max_width'     => array( 'size' => 620, 'unit' => 'px' ),
							'cinematic_effect'      => '',
						),
					),
				),
			),

			'hero-light' => array(
				'title'       => 'Hero Light',
				'description' => 'Clean minimal hero with white content box',
				'category'    => 'hero',
				'thumbnail'   => 'https://picsum.photos/seed/hero-light/400/225',
				'settings'    => array(
					'content_source'        => 'custom',
					'effect'                => 'slide',
					'autoplay'              => 'yes',
					'delay'                 => 5000,
					'speed'                 => 800,
					'loop'                  => 'yes',
					'arrows'                => 'yes',
					'pagination_type'       => 'bullets',
					'slider_height'         => array( 'size' => 90, 'unit' => 'vh' ),
					'content_bg'            => 'rgba(255,255,255,0.95)',
					'content_glass_effect'  => '',
					'content_alignment'     => 'left',
					'content_radius'        => array(
						'top' => 8, 'right' => 8, 'bottom' => 8, 'left' => 8, 'unit' => 'px',
					),
					'heading_color'         => '#111111',
					'text_color'            => '#555555',
					'btn_bg'                => '#111111',
					'btn_color'             => '#ffffff',
					'btn_bg_hover'          => '#333333',
					'btn_border_radius'     => array( 'size' => 4 ),
					'slides_data'           => array(
						array(
							'media_type'         => 'image',
							'bg_image'           => array( 'url' => 'https://picsum.photos/seed/light1/1920/1080' ),
							'image_fit'          => 'cover',
							'image_position'     => 'right center',
							'image_effect'       => 'none',
							'overlay_type'       => 'none',
							'heading'            => 'Welcome to the Future',
							'heading_tag'        => 'h2',
							'description'        => 'Clean, modern design that speaks for itself. No noise, just clarity.',
							'animation'          => 'fade-right',
							'btn_text'           => 'Explore Now',
							'btn_url'            => array( 'url' => '#' ),
							'content_align'      => 'left',
							'content_vertical'   => 'middle',
							'content_box_enable' => 'yes',
							'content_max_width'  => array( 'size' => 460, 'unit' => 'px' ),
							'cinematic_effect'   => '',
						),
						array(
							'media_type'         => 'image',
							'bg_image'           => array( 'url' => 'https://picsum.photos/seed/light2/1920/1080' ),
							'image_fit'          => 'cover',
							'image_position'     => 'left center',
							'image_effect'       => 'none',
							'overlay_type'       => 'none',
							'heading'            => 'Designed to Inspire',
							'heading_tag'        => 'h2',
							'description'        => 'Every detail crafted with purpose. Every interaction meaningful.',
							'animation'          => 'fade-up',
							'btn_text'           => 'See More',
							'btn_url'            => array( 'url' => '#' ),
							'content_align'      => 'left',
							'content_vertical'   => 'middle',
							'content_box_enable' => 'yes',
							'content_max_width'  => array( 'size' => 460, 'unit' => 'px' ),
							'cinematic_effect'   => '',
						),
					),
				),
			),

			'testimonial' => array(
				'title'       => 'Testimonial',
				'description' => 'Quote-style with glass morphism content box',
				'category'    => 'testimonial',
				'thumbnail'   => 'https://picsum.photos/seed/testimonial/400/225',
				'settings'    => array(
					'content_source'       => 'custom',
					'effect'               => 'fade',
					'autoplay'             => 'yes',
					'delay'                => 7000,
					'speed'                => 1200,
					'loop'                 => 'yes',
					'arrows'               => 'yes',
					'pagination_type'      => 'bullets',
					'slider_height'        => array( 'size' => 600, 'unit' => 'px' ),
					'content_bg'           => 'rgba(255,255,255,0.12)',
					'content_glass_effect' => 'yes',
					'content_glass_blur'   => array( 'size' => 16 ),
					'content_alignment'    => 'center',
					'content_radius'       => array(
						'top' => 16, 'right' => 16, 'bottom' => 16, 'left' => 16, 'unit' => 'px',
					),
					'heading_color'        => '#ffffff',
					'text_color'           => 'rgba(255,255,255,0.9)',
					'btn_bg'               => 'transparent',
					'btn_color'            => '#ffffff',
					'btn_bg_hover'         => 'rgba(255,255,255,0.2)',
					'btn_border_radius'    => array( 'size' => 30 ),
					'slides_data'          => array(
						array(
							'media_type'            => 'image',
							'bg_image'              => array( 'url' => 'https://picsum.photos/seed/testi1/1920/1080' ),
							'image_fit'             => 'cover',
							'image_position'        => 'center center',
							'image_effect'          => 'zoom',
							'overlay_type'          => 'gradient',
							'overlay_gradient_start'=> 'rgba(30,30,80,0.8)',
							'overlay_gradient_end'  => 'rgba(80,30,60,0.6)',
							'overlay_gradient_direction' => 'to right',
							'heading'               => '"This product changed everything for our team."',
							'heading_tag'           => 'h3',
							'description'           => '— Sarah Johnson, CEO at TechCorp',
							'animation'             => 'fade-up',
							'btn_text'              => 'Read Full Story',
							'btn_url'               => array( 'url' => '#' ),
							'content_align'         => 'center',
							'content_vertical'      => 'middle',
							'content_box_enable'    => 'yes',
							'content_max_width'     => array( 'size' => 640, 'unit' => 'px' ),
							'cinematic_effect'      => 'yes',
						),
						array(
							'media_type'            => 'image',
							'bg_image'              => array( 'url' => 'https://picsum.photos/seed/testi2/1920/1080' ),
							'image_fit'             => 'cover',
							'image_position'        => 'center center',
							'image_effect'          => 'parallax',
							'overlay_type'          => 'gradient',
							'overlay_gradient_start'=> 'rgba(20,60,40,0.8)',
							'overlay_gradient_end'  => 'rgba(60,20,80,0.5)',
							'overlay_gradient_direction' => 'to right',
							'heading'               => '"Incredible results within the first month of use."',
							'heading_tag'           => 'h3',
							'description'           => '— Mark Williams, Founder at StartupXYZ',
							'animation'             => 'zoom-in',
							'btn_text'              => 'Read Full Story',
							'btn_url'               => array( 'url' => '#' ),
							'content_align'         => 'center',
							'content_vertical'      => 'middle',
							'content_box_enable'    => 'yes',
							'content_max_width'     => array( 'size' => 640, 'unit' => 'px' ),
							'cinematic_effect'      => '',
						),
					),
				),
			),

			'portfolio' => array(
				'title'       => 'Portfolio',
				'description' => 'Image-focused, minimal overlay, bottom-aligned text',
				'category'    => 'portfolio',
				'thumbnail'   => 'https://picsum.photos/seed/portfolio/400/225',
				'settings'    => array(
					'content_source'        => 'custom',
					'effect'                => 'slide',
					'autoplay'              => 'yes',
					'delay'                 => 5000,
					'speed'                 => 700,
					'loop'                  => 'yes',
					'arrows'                => 'yes',
					'pagination_type'       => 'fraction',
					'thumbnail_nav'         => 'yes',
					'thumb_height'          => array( 'size' => 70, 'unit' => 'px' ),
					'slider_height'         => array( 'size' => 80, 'unit' => 'vh' ),
					'content_bg'            => 'rgba(0,0,0,0)',
					'content_glass_effect'  => '',
					'content_alignment'     => 'left',
					'heading_color'         => '#ffffff',
					'text_color'            => 'rgba(255,255,255,0.75)',
					'btn_bg'                => 'transparent',
					'btn_color'             => '#ffffff',
					'btn_bg_hover'          => 'rgba(255,255,255,0.15)',
					'btn_border_radius'     => array( 'size' => 0 ),
					'slides_data'           => array(
						array(
							'media_type'         => 'image',
							'bg_image'           => array( 'url' => 'https://picsum.photos/seed/port1/1920/1080' ),
							'image_fit'          => 'cover',
							'image_position'     => 'center center',
							'image_effect'       => 'zoom',
							'overlay_type'       => 'gradient',
							'overlay_gradient_start' => 'rgba(0,0,0,0.7)',
							'overlay_gradient_end'   => 'rgba(0,0,0,0)',
							'overlay_gradient_direction' => 'to top',
							'badge_text'         => 'Branding',
							'badge_color'        => '#ffffff',
							'heading'            => 'Project Alpha',
							'heading_tag'        => 'h3',
							'description'        => 'Visual identity & brand strategy for a global tech company.',
							'animation'          => 'fade-up',
							'btn_text'           => 'View Project →',
							'btn_url'            => array( 'url' => '#' ),
							'content_align'      => 'left',
							'content_vertical'   => 'bottom',
							'content_box_enable' => 'yes',
							'content_max_width'  => array( 'size' => 500, 'unit' => 'px' ),
							'cinematic_effect'   => '',
						),
						array(
							'media_type'         => 'image',
							'bg_image'           => array( 'url' => 'https://picsum.photos/seed/port2/1920/1080' ),
							'image_fit'          => 'cover',
							'image_position'     => 'center center',
							'image_effect'       => 'parallax',
							'overlay_type'       => 'gradient',
							'overlay_gradient_start' => 'rgba(0,0,0,0.65)',
							'overlay_gradient_end'   => 'rgba(0,0,0,0)',
							'overlay_gradient_direction' => 'to top',
							'badge_text'         => 'Web Design',
							'badge_color'        => '#ffffff',
							'heading'            => 'Project Beta',
							'heading_tag'        => 'h3',
							'description'        => 'Full-stack e-commerce platform with custom design system.',
							'animation'          => 'fade-up',
							'btn_text'           => 'View Project →',
							'btn_url'            => array( 'url' => '#' ),
							'content_align'      => 'left',
							'content_vertical'   => 'bottom',
							'content_box_enable' => 'yes',
							'content_max_width'  => array( 'size' => 500, 'unit' => 'px' ),
							'cinematic_effect'   => '',
						),
						array(
							'media_type'         => 'image',
							'bg_image'           => array( 'url' => 'https://picsum.photos/seed/port3/1920/1080' ),
							'image_fit'          => 'cover',
							'image_position'     => 'center center',
							'image_effect'       => 'zoom',
							'overlay_type'       => 'gradient',
							'overlay_gradient_start' => 'rgba(0,0,0,0.7)',
							'overlay_gradient_end'   => 'rgba(0,0,0,0)',
							'overlay_gradient_direction' => 'to top',
							'badge_text'         => 'Motion',
							'badge_color'        => '#ffffff',
							'heading'            => 'Project Gamma',
							'heading_tag'        => 'h3',
							'description'        => 'Motion graphics & animation for product launch campaign.',
							'animation'          => 'fade-up',
							'btn_text'           => 'View Project →',
							'btn_url'            => array( 'url' => '#' ),
							'content_align'      => 'left',
							'content_vertical'   => 'bottom',
							'content_box_enable' => 'yes',
							'content_max_width'  => array( 'size' => 500, 'unit' => 'px' ),
							'cinematic_effect'   => '',
						),
					),
				),
			),

			'corporate' => array(
				'title'       => 'Corporate',
				'description' => 'Professional, clean, centered content',
				'category'    => 'corporate',
				'thumbnail'   => 'https://picsum.photos/seed/corporate/400/225',
				'settings'    => array(
					'content_source'        => 'custom',
					'effect'                => 'fade',
					'autoplay'              => 'yes',
					'delay'                 => 6000,
					'speed'                 => 900,
					'loop'                  => 'yes',
					'arrows'                => 'yes',
					'pagination_type'       => 'bullets',
					'slider_height'         => array( 'size' => 85, 'unit' => 'vh' ),
					'content_bg'            => 'rgba(255,255,255,0.1)',
					'content_glass_effect'  => 'yes',
					'content_glass_blur'    => array( 'size' => 10 ),
					'content_alignment'     => 'center',
					'content_radius'        => array( 'top' => 8, 'right' => 8, 'bottom' => 8, 'left' => 8, 'unit' => 'px' ),
					'heading_color'         => '#ffffff',
					'text_color'            => 'rgba(255,255,255,0.88)',
					'btn_bg'                => '#0066cc',
					'btn_color'             => '#ffffff',
					'btn_bg_hover'          => '#0052a3',
					'btn_border_radius'     => array( 'size' => 4 ),
					'slides_data'           => array(
						array(
							'media_type'         => 'image',
							'bg_image'           => array( 'url' => 'https://picsum.photos/seed/corp1/1920/1080' ),
							'image_fit'          => 'cover',
							'image_position'     => 'center center',
							'image_effect'       => 'zoom',
							'overlay_type'       => 'solid',
							'overlay_color'      => 'rgba(0,30,80,0.65)',
							'heading'            => 'Trusted by 500+ Companies',
							'heading_tag'        => 'h2',
							'description'        => 'We deliver enterprise-grade solutions with measurable impact.',
							'animation'          => 'fade-up',
							'btn_text'           => 'Schedule a Demo',
							'btn_url'            => array( 'url' => '#' ),
							'content_align'      => 'center',
							'content_vertical'   => 'middle',
							'content_box_enable' => 'yes',
							'content_max_width'  => array( 'size' => 600, 'unit' => 'px' ),
							'cinematic_effect'   => 'yes',
						),
						array(
							'media_type'         => 'image',
							'bg_image'           => array( 'url' => 'https://picsum.photos/seed/corp2/1920/1080' ),
							'image_fit'          => 'cover',
							'image_position'     => 'center center',
							'image_effect'       => 'parallax',
							'overlay_type'       => 'solid',
							'overlay_color'      => 'rgba(0,20,60,0.6)',
							'heading'            => '20 Years of Excellence',
							'heading_tag'        => 'h2',
							'description'        => 'Building long-term partnerships through innovation and reliability.',
							'animation'          => 'fade-up',
							'btn_text'           => 'Our Story',
							'btn_url'            => array( 'url' => '#' ),
							'content_align'      => 'center',
							'content_vertical'   => 'middle',
							'content_box_enable' => 'yes',
							'content_max_width'  => array( 'size' => 600, 'unit' => 'px' ),
							'cinematic_effect'   => '',
						),
					),
				),
			),

			'news-blog' => array(
				'title'       => 'News / Blog',
				'description' => 'Dynamic posts — pulls latest posts automatically',
				'category'    => 'dynamic',
				'thumbnail'   => 'https://picsum.photos/seed/news/400/225',
				'settings'    => array(
					'content_source'       => 'posts',
					'query_post_type'      => 'post',
					'query_posts_per_page' => 5,
					'query_orderby'        => 'date',
					'query_order'          => 'DESC',
					'query_animation'      => 'fade-up',
					'query_btn_text'       => 'Read More',
					'query_overlay_color'  => 'rgba(0,0,0,0.55)',
					'effect'               => 'slide',
					'autoplay'             => 'yes',
					'delay'                => 5000,
					'speed'                => 800,
					'loop'                 => 'yes',
					'arrows'               => 'yes',
					'pagination_type'      => 'fraction',
					'thumbnail_nav'        => 'yes',
					'thumb_height'         => array( 'size' => 65, 'unit' => 'px' ),
					'slider_height'        => array( 'size' => 70, 'unit' => 'vh' ),
					'content_bg'           => 'rgba(0,0,0,0)',
					'content_glass_effect' => '',
					'content_alignment'    => 'left',
					'heading_color'        => '#ffffff',
					'text_color'           => 'rgba(255,255,255,0.85)',
					'btn_bg'               => '#ffffff',
					'btn_color'            => '#111111',
					'btn_bg_hover'         => '#f0f0f0',
					'btn_border_radius'    => array( 'size' => 4 ),
					'slides_data'          => array(),
				),
			),

			'woocommerce' => array(
				'title'       => 'WooCommerce Products',
				'description' => 'Dynamic product slider with sale badges',
				'category'    => 'dynamic',
				'thumbnail'   => 'https://picsum.photos/seed/woo/400/225',
				'settings'    => array(
					'content_source'        => 'products',
					'woo_products_per_page' => 5,
					'woo_orderby'           => 'date',
					'woo_show_price'        => 'yes',
					'woo_show_sale_badge'   => 'yes',
					'woo_btn_type'          => 'view',
					'woo_overlay_color'     => 'rgba(0,0,0,0.4)',
					'effect'                => 'fade',
					'autoplay'              => 'yes',
					'delay'                 => 5000,
					'speed'                 => 900,
					'loop'                  => 'yes',
					'arrows'                => 'yes',
					'pagination_type'       => 'bullets',
					'slider_height'         => array( 'size' => 75, 'unit' => 'vh' ),
					'content_bg'            => 'rgba(0,0,0,0)',
					'content_glass_effect'  => '',
					'content_alignment'     => 'center',
					'heading_color'         => '#ffffff',
					'text_color'            => 'rgba(255,255,255,0.9)',
					'btn_bg'                => '#e74c3c',
					'btn_color'             => '#ffffff',
					'btn_bg_hover'          => '#c0392b',
					'btn_border_radius'     => array( 'size' => 4 ),
					'slides_data'           => array(),
				),
			),

			'split-hero' => array(
				'title'       => 'Split Hero',
				'description' => 'Half image, half content — unique layout',
				'category'    => 'hero',
				'thumbnail'   => 'https://picsum.photos/seed/split/400/225',
				'settings'    => array(
					'content_source'  => 'custom',
					'effect'          => 'slide',
					'autoplay'        => 'yes',
					'delay'           => 6000,
					'speed'           => 900,
					'loop'            => 'yes',
					'arrows'          => 'yes',
					'pagination_type' => 'bullets',
					'tilt_effect'     => 'yes',
					'tilt_intensity'  => array( 'size' => 6 ),
					'tilt_glare'      => 'yes',
					'slider_height'   => array( 'size' => 100, 'unit' => 'vh' ),
					'slides_data'     => array(
						array(
							'_id'              => 'splithero1',
							'media_type'       => 'image',
							'bg_image'         => array( 'url' => 'https://picsum.photos/seed/split1/1920/1080' ),
							'split_screen'     => 'yes',
							'split_ratio'      => '55-45',
							'split_reverse'    => '',
							'split_diagonal'   => 'yes',
							'split_content_bg' => '#1a1a2e',
							'badge_text'       => 'New',
							'badge_color'      => '#6c63ff',
							'heading'          => 'Designed for Impact',
							'heading_tag'      => 'h2',
							'description'      => 'Create stunning presentations that captivate your audience and drive real results.',
							'anim_heading'     => 'fade-right',
							'anim_text'        => 'fade-right',
							'anim_btn'         => 'fade-right',
							'btn_text'         => 'Get Started',
							'btn_url'          => array( 'url' => '#' ),
							'overlay_type'     => 'none',
						),
						array(
							'_id'              => 'splithero2',
							'media_type'       => 'image',
							'bg_image'         => array( 'url' => 'https://picsum.photos/seed/split2/1920/1080' ),
							'split_screen'     => 'yes',
							'split_ratio'      => '55-45',
							'split_reverse'    => 'yes',
							'split_diagonal'   => 'yes',
							'split_content_bg' => '#0f3460',
							'badge_text'       => 'Featured',
							'badge_color'      => '#e74c3c',
							'heading'          => 'Built to Perform',
							'heading_tag'      => 'h2',
							'description'      => 'Engineered for speed, designed for beauty. Every pixel crafted with purpose.',
							'anim_heading'     => 'fade-left',
							'anim_text'        => 'fade-left',
							'anim_btn'         => 'fade-left',
							'btn_text'         => 'Learn More',
							'btn_url'          => array( 'url' => '#' ),
							'overlay_type'     => 'none',
						),
					),
				),
			),

			'typing-hero' => array(
				'title'       => 'Typing Hero',
				'description' => 'Auto-typing heading with cinematic background',
				'category'    => 'hero',
				'thumbnail'   => 'https://picsum.photos/seed/typing/400/225',
				'settings'    => array(
					'content_source'       => 'custom',
					'effect'               => 'fade',
					'autoplay'             => 'yes',
					/* Slower, readable transitions (Swiper speed ms; slider height uses responsive control above). */
					'delay'                => 9000,
					'speed'                => 1400,
					'loop'                 => 'yes',
					'arrows'               => 'yes',
					'pagination_type'      => 'bullets',
					/* Tilt fights fade transitions; keep this template clean */
					'tilt_effect'          => '',
					'tilt_intensity'       => array( 'size' => 8 ),
					'tilt_glare'           => 'yes',
					'slider_height'        => array( 'size' => 100, 'unit' => 'vh' ),
					/* Empty = no Elementor color rule on content box (avoids opaque white after import) */
					'content_bg'           => '',
					'content_glass_effect' => '',
					'content_alignment'    => 'center',
					'heading_color'        => '#ffffff',
					'text_color'           => 'rgba(255,255,255,0.85)',
					'btn_bg'               => '#6c63ff',
					'btn_color'            => '#ffffff',
					'btn_bg_hover'         => '#5650d4',
					'btn_border_radius'    => array( 'size' => 6 ),
					/* Two slides so Swiper loop/fade behaves reliably (single-slide loop can flash empty) */
					'slides_data'          => array(
						array(
							'_id'                        => 'typinghero1',
							'media_type'                 => 'image',
							'bg_image'                   => array( 'url' => 'https://picsum.photos/seed/type1/1920/1080' ),
							'image_fit'                  => 'cover',
							'image_position'             => 'center center',
							'image_effect'               => 'zoom',
							'overlay_type'               => 'gradient',
							'overlay_gradient_start'     => 'rgba(0,0,0,0.78)',
							'overlay_gradient_end'       => 'rgba(0,0,0,0.25)',
							'overlay_gradient_direction' => 'to top',
							'typing_effect'              => 'yes',
							'typing_strings'             => "We build amazing things\nWe create stunning designs\nWe deliver real results",
							'typing_speed'               => 75,
							'typing_delete_speed'        => 40,
							'typing_pause'               => 2000,
							'heading'                    => 'We build amazing things',
							'heading_tag'                => 'h1',
							'description'                => 'A creative agency focused on delivering exceptional digital experiences.',
							'anim_heading'               => 'fade-up',
							'anim_text'                  => 'fade-up',
							'anim_btn'                   => 'fade-up',
							'anim_heading_delay'         => 0,
							'anim_text_delay'            => 200,
							'anim_btn_delay'             => 400,
							'btn_text'                   => 'Start Your Journey',
							'btn_url'                    => array( 'url' => '#' ),
							'content_align'              => 'center',
							'content_vertical'           => 'middle',
							'content_box_enable'         => 'yes',
							'content_max_width'          => array( 'size' => 640, 'unit' => 'px' ),
							'cinematic_effect'           => 'yes',
						),
						array(
							'_id'                        => 'typinghero2',
							'media_type'                 => 'image',
							'bg_image'                   => array( 'url' => 'https://picsum.photos/seed/type2/1920/1080' ),
							'image_fit'                  => 'cover',
							'image_position'             => 'center center',
							'image_effect'               => 'zoom',
							'overlay_type'               => 'gradient',
							'overlay_gradient_start'     => 'rgba(0,0,0,0.78)',
							'overlay_gradient_end'       => 'rgba(0,0,0,0.25)',
							'overlay_gradient_direction' => 'to top',
							'typing_effect'              => 'yes',
							'typing_strings'             => "Innovation meets craft\nDesign that converts\nYour story, elevated",
							'typing_speed'               => 75,
							'typing_delete_speed'        => 40,
							'typing_pause'               => 2000,
							'heading'                    => 'Innovation meets craft',
							'heading_tag'                => 'h1',
							'description'                => 'Partnerships that turn bold ideas into refined digital products.',
							'anim_heading'               => 'fade-up',
							'anim_text'                  => 'fade-up',
							'anim_btn'                   => 'fade-up',
							'anim_heading_delay'         => 0,
							'anim_text_delay'            => 200,
							'anim_btn_delay'             => 400,
							'btn_text'                   => 'Explore Work',
							'btn_url'                    => array( 'url' => '#' ),
							'content_align'              => 'center',
							'content_vertical'           => 'middle',
							'content_box_enable'         => 'yes',
							'content_max_width'          => array( 'size' => 640, 'unit' => 'px' ),
							'cinematic_effect'           => 'yes',
						),
					),
				),
			),

			'glitter-hero' => array(
				'title'       => 'Glitter Hero',
				'description' => 'Gold glitter particles — luxury feel',
				'category'    => 'hero',
				'thumbnail'   => 'https://picsum.photos/seed/glitter/400/225',
				'settings'    => array(
					'content_source'        => 'custom',
					'effect'                => 'fade',
					'autoplay'              => 'yes',
					'delay'                 => 6000,
					'speed'                 => 1000,
					'loop'                  => 'yes',
					'arrows'                => 'yes',
					'pagination_type'       => 'bullets',
					'slider_height'         => array( 'size' => 100, 'unit' => 'vh' ),
					'content_bg'            => 'rgba(0,0,0,0)',
					'content_glass_effect' => 'yes',
					'content_glass_blur'    => array( 'size' => 12 ),
					'content_alignment'    => 'center',
					'heading_color'        => '#ffd700',
					'text_color'           => 'rgba(255,255,255,0.88)',
					'btn_bg'               => '#ffd700',
					'btn_color'            => '#1a1a2e',
					'btn_bg_hover'         => '#ffec8b',
					'btn_border_radius'   => array( 'size' => 30 ),
					'slides_data'          => array(
						array(
							'media_type'         => 'image',
							'bg_image'           => array( 'url' => 'https://picsum.photos/seed/glitter1/1920/1080' ),
							'image_effect'       => 'zoom',
							'overlay_type'       => 'solid',
							'overlay_color'      => 'rgba(10,5,30,0.75)',
							'particle_enable'    => 'yes',
							'particle_preset'    => 'glitter',
							'heading'            => 'Luxury. Redefined.',
							'heading_tag'        => 'h1',
							'description'        => 'Experience the finest craftsmanship in every detail.',
							'anim_heading'       => 'fade-up',
							'anim_text'          => 'fade-up',
							'anim_btn'           => 'fade-up',
							'anim_heading_delay' => 0,
							'anim_text_delay'    => 150,
							'anim_btn_delay'     => 300,
							'btn_text'           => 'Discover More',
							'btn_url'            => array( 'url' => '#' ),
							'content_align'      => 'center',
							'content_vertical'   => 'middle',
							'content_box_enable' => 'yes',
							'content_max_width'  => array( 'size' => 580, 'unit' => 'px' ),
							'cinematic_effect'   => 'yes',
						),
						array(
							'media_type'         => 'image',
							'bg_image'           => array( 'url' => 'https://picsum.photos/seed/glitter2/1920/1080' ),
							'image_effect'       => 'parallax',
							'overlay_type'       => 'gradient',
							'overlay_gradient_start'     => 'rgba(20,5,40,0.8)',
							'overlay_gradient_end'       => 'rgba(5,5,20,0.5)',
							'overlay_gradient_direction' => 'to top',
							'particle_enable'    => 'yes',
							'particle_preset'    => 'stars',
							'heading'            => 'Crafted to Perfection',
							'heading_tag'        => 'h1',
							'description'        => 'Where elegance meets innovation in every single moment.',
							'anim_heading'       => 'zoom-in',
							'anim_text'          => 'fade-up',
							'anim_btn'           => 'fade-up',
							'anim_heading_delay' => 0,
							'anim_text_delay'    => 200,
							'anim_btn_delay'     => 350,
							'btn_text'           => 'Explore Now',
							'btn_url'            => array( 'url' => '#' ),
							'content_align'      => 'center',
							'content_vertical'   => 'middle',
							'content_box_enable' => 'yes',
							'content_max_width'  => array( 'size' => 580, 'unit' => 'px' ),
							'cinematic_effect'   => '',
						),
					),
				),
			),

			'snow-hero' => array(
				'title'       => 'Snow Hero',
				'description' => 'Falling snow particles — elegant winter feel',
				'category'    => 'hero',
				'thumbnail'   => 'https://picsum.photos/seed/snow/400/225',
				'settings'    => array(
					'content_source'        => 'custom',
					'effect'                => 'fade',
					'autoplay'              => 'yes',
					'delay'                 => 7000,
					'speed'                 => 1200,
					'loop'                  => 'yes',
					'arrows'                => 'yes',
					'pagination_type'       => 'bullets',
					'slider_height'         => array( 'size' => 100, 'unit' => 'vh' ),
					'content_bg'            => 'rgba(255,255,255,0.08)',
					'content_glass_effect' => 'yes',
					'content_glass_blur'    => array( 'size' => 10 ),
					'content_alignment'    => 'center',
					'heading_color'        => '#ffffff',
					'text_color'           => 'rgba(255,255,255,0.85)',
					'btn_bg'               => '#ffffff',
					'btn_color'            => '#1a1a2e',
					'btn_bg_hover'         => '#f0f0f0',
					'btn_border_radius'   => array( 'size' => 6 ),
					'slides_data'          => array(
						array(
							'media_type'         => 'image',
							'bg_image'           => array( 'url' => 'https://picsum.photos/seed/snow1/1920/1080' ),
							'image_effect'       => 'zoom',
							'overlay_type'       => 'solid',
							'overlay_color'      => 'rgba(0,20,50,0.6)',
							'particle_enable'    => 'yes',
							'particle_preset'    => 'snow',
							'heading'            => 'Pure. Simple. Beautiful.',
							'heading_tag'        => 'h1',
							'description'        => 'Minimalist design that lets your content breathe and shine.',
							'anim_heading'       => 'fade-up',
							'anim_text'          => 'fade-up',
							'anim_btn'           => 'fade-up',
							'anim_heading_delay' => 0,
							'anim_text_delay'    => 150,
							'anim_btn_delay'     => 300,
							'btn_text'           => 'Get Started',
							'btn_url'            => array( 'url' => '#' ),
							'content_align'      => 'center',
							'content_vertical'   => 'middle',
							'content_box_enable' => 'yes',
							'content_max_width'  => array( 'size' => 560, 'unit' => 'px' ),
							'cinematic_effect'   => 'yes',
						),
					),
				),
			),

			'countdown-offer' => array(
				'title'       => 'Countdown Offer',
				'description' => 'Limited time offer with live countdown',
				'category'    => 'hero',
				'thumbnail'   => 'https://picsum.photos/seed/countdown/400/225',
				'settings'    => array(
					'content_source'        => 'custom',
					'effect'                => 'fade',
					'autoplay'              => 'no',
					'loop'                  => 'yes',
					'arrows'                => 'yes',
					'pagination_type'       => 'bullets',
					'slider_height'         => array( 'size' => 100, 'unit' => 'vh' ),
					'content_bg'            => 'rgba(0,0,0,0)',
					'content_glass_effect' => 'yes',
					'content_glass_blur'    => array( 'size' => 14 ),
					'content_alignment'    => 'center',
					'heading_color'        => '#ffffff',
					'text_color'           => 'rgba(255,255,255,0.88)',
					'btn_bg'               => '#e74c3c',
					'btn_color'            => '#ffffff',
					'btn_bg_hover'         => '#c0392b',
					'btn_border_radius'   => array( 'size' => 6 ),
					'slides_data'          => array(
						array(
							'media_type'          => 'image',
							'bg_image'            => array( 'url' => 'https://picsum.photos/seed/offer1/1920/1080' ),
							'image_effect'        => 'zoom',
							'overlay_type'        => 'gradient',
							'overlay_gradient_start' => 'rgba(0,0,0,0.8)',
							'overlay_gradient_end'   => 'rgba(20,0,40,0.5)',
							'overlay_gradient_direction' => 'to top',
							'particle_enable'     => 'yes',
							'particle_preset'     => 'glitter',
							'badge_text'          => 'Limited Time',
							'badge_color'         => '#e74c3c',
							'heading'             => 'Mega Sale — 50% Off',
							'heading_tag'         => 'h1',
							'description'         => 'Hurry! This exclusive offer expires soon. Grab it before it\'s gone.',
							'countdown_enable'    => 'yes',
							'countdown_date'      => gmdate( 'Y-m-d H:i', strtotime( '+3 days' ) ),
							'countdown_style'     => 'blocks',
							'countdown_position'  => 'below-content',
							'countdown_action'    => 'message',
							'countdown_expired_msg' => 'Offer Ended!',
							'countdown_urgency'   => 'yes',
							'anim_heading'        => 'fade-up',
							'anim_text'           => 'fade-up',
							'anim_btn'            => 'fade-up',
							'anim_heading_delay' => 0,
							'anim_text_delay'    => 150,
							'anim_btn_delay'     => 300,
							'btn_text'            => 'Claim Offer Now',
							'btn_url'             => array( 'url' => '#' ),
							'content_align'      => 'center',
							'content_vertical'   => 'middle',
							'content_box_enable' => 'yes',
							'content_max_width'  => array( 'size' => 620, 'unit' => 'px' ),
							'cinematic_effect'   => 'yes',
						),
					),
				),
			),

			'book-showcase' => array(
				'title'       => 'Book Showcase',
				'description' => 'Left content + right 2x2 book grid with animations',
				'category'    => 'portfolio',
				'thumbnail'   => 'https://picsum.photos/seed/books/400/225',
				'settings'    => array(
					'content_source'    => 'custom',
					'effect'            => 'fade',
					'autoplay'          => 'yes',
					'delay'             => 7000,
					'speed'             => 1000,
					'loop'              => 'yes',
					'arrows'            => 'yes',
					'pagination_type'   => 'bullets',
					'slider_height'     => array( 'size' => 90, 'unit' => 'vh' ),
					'content_bg'        => 'rgba(0,0,0,0)',
					'content_alignment' => 'left',
					'heading_color'     => '#ffffff',
					'text_color'        => 'rgba(255,255,255,0.85)',
					'btn_bg'            => '#4a5d32',
					'btn_color'         => '#ffffff',
					'btn_bg_hover'      => '#3d4d28',
					'btn_border_radius' => array( 'size' => 6 ),
					'slides_data'       => array(
						array(
							'media_type'         => 'image',
							'bg_image'           => array( 'url' => 'https://picsum.photos/seed/bookbg1/1920/1080' ),
							'image_fit'          => 'cover',
							'image_position'     => 'center center',
							'image_effect'       => 'none',
							'overlay_type'       => 'solid',
							'overlay_color'      => 'rgba(10,40,20,0.82)',

							'book_layout_enable'   => 'yes',
							'book_content_ratio'   => '50-50',
							'book_show_title'      => 'yes',
							'book_float_animation' => 'yes',
							'book_card_bg'         => 'rgba(0,0,0,0)',
							'book_title_color'     => '#fff',
							'book_heading_highlight' => 'আলোকিত',
							'book_btn2_text'       => 'সকল বই দেখুন',
							'book_btn2_url'        => array( 'url' => '#' ),

							'book1_image' => array( 'url' => 'https://picsum.photos/seed/book1/300/400' ),
							'book1_title' => 'অদৃশ্য সাম্রাজ্য',
							'book1_url'   => array( 'url' => '#' ),

							'book2_image' => array( 'url' => 'https://picsum.photos/seed/book2/300/400' ),
							'book2_title' => 'ইসলাম ও মুসলমানের পরিচয়',
							'book2_url'   => array( 'url' => '#' ),

							'book3_image' => array( 'url' => 'https://picsum.photos/seed/book3/300/400' ),
							'book3_title' => 'অভিশপ্ত রংধনু',
							'book3_url'   => array( 'url' => '#' ),

							'book4_image' => array( 'url' => 'https://picsum.photos/seed/book4/300/400' ),
							'book4_title' => 'ইতিহাসের আয়নায় ইহুদি-খ্রিষ্টান',
							'book4_url'   => array( 'url' => '#' ),

							'badge_text'         => '৫০+ প্রকাশিত ইসলামী গ্রন্থ',
							'badge_color'        => 'rgba(45,55,30,0.92)',
							'heading'            => 'জ্ঞানের আলোয় আলোকিত হোক প্রতিটি ঘর',
							'heading_tag'        => 'h1',
							'description'        => 'মাকতাবাতুন নূরের নতুন ও সেরা বইগুলো সংগ্রহ করুন আজই। প্রখ্যাত আলেমদের লেখনীতে সমৃদ্ধ হোক আপনার লাইব্রেরি।',
							'anim_heading'       => 'fade-right',
							'anim_text'          => 'fade-right',
							'anim_btn'           => 'fade-up',
							'anim_heading_delay' => 0,
							'anim_text_delay'    => 180,
							'anim_btn_delay'     => 320,
							'btn_text'           => 'সেরা বইগুলো দেখুন',
							'btn_url'            => array( 'url' => '#' ),
							'content_vertical'   => 'middle',
							'content_max_width'  => array( 'size' => 560, 'unit' => 'px' ),
							'cinematic_effect'   => '',
						),
					),
				),
			),

			'fullscreen-scroll' => array(
				'title'       => 'Fullscreen Scroll',
				'description' => 'Scroll to navigate — immersive fullscreen experience',
				'category'    => 'hero',
				'thumbnail'   => 'https://picsum.photos/seed/scroll/400/225',
				'settings'    => array(
					'content_source'            => 'custom',
					'effect'                    => 'slide',
					'autoplay'                  => '',
					'loop'                      => '',
					'arrows'                    => '',
					'pagination_type'           => 'none',
					'mousewheel_enable'         => 'yes',
					'mousewheel_sensitivity'    => array( 'size' => 1 ),
					'mousewheel_indicator'      => 'yes',
					'mousewheel_indicator_text' => 'Scroll to explore',
					'mousewheel_progress'       => 'yes',
					'tilt_effect'               => 'yes',
					'tilt_intensity'            => array( 'size' => 5 ),
					'tilt_glare'                => 'yes',
					'slider_height'             => array( 'size' => 100, 'unit' => 'vh' ),
					'content_bg'                => 'rgba(0,0,0,0)',
					'content_glass_effect'      => '',
					'content_alignment'         => 'left',
					'heading_color'             => '#ffffff',
					'text_color'                => 'rgba(255,255,255,0.85)',
					'btn_bg'                    => 'transparent',
					'btn_color'                 => '#ffffff',
					'btn_bg_hover'              => 'rgba(255,255,255,0.15)',
					'btn_border_radius'         => array( 'size' => 4 ),
					'slides_data'               => array(
						array(
							'media_type'                 => 'image',
							'bg_image'                   => array( 'url' => 'https://picsum.photos/seed/scroll1/1920/1080' ),
							'image_effect'               => 'zoom',
							'overlay_type'               => 'gradient',
							'overlay_gradient_start'     => 'rgba(0,0,0,0.6)',
							'overlay_gradient_end'       => 'rgba(0,0,0,0.1)',
							'overlay_gradient_direction' => 'to top',
							'heading'                    => 'Chapter One',
							'heading_tag'                => 'h2',
							'description'                => 'Scroll down to continue the journey.',
							'anim_heading'               => 'fade-up',
							'anim_text'                  => 'fade-up',
							'anim_btn'                   => 'fade-up',
							'anim_heading_delay'         => 0,
							'anim_text_delay'            => 150,
							'anim_btn_delay'             => 300,
							'btn_text'                   => 'Explore →',
							'btn_url'                    => array( 'url' => '#' ),
							'content_align'              => 'left',
							'content_vertical'           => 'middle',
							'content_box_enable'         => 'yes',
							'content_max_width'          => array( 'size' => 520, 'unit' => 'px' ),
							'cinematic_effect'           => 'yes',
						),
						array(
							'media_type'                 => 'image',
							'bg_image'                   => array( 'url' => 'https://picsum.photos/seed/scroll2/1920/1080' ),
							'image_effect'               => 'parallax',
							'overlay_type'               => 'gradient',
							'overlay_gradient_start'     => 'rgba(0,0,0,0.65)',
							'overlay_gradient_end'       => 'rgba(0,0,0,0.1)',
							'overlay_gradient_direction' => 'to top',
							'heading'                    => 'Chapter Two',
							'heading_tag'                => 'h2',
							'description'                => 'Every scroll tells a deeper story.',
							'anim_heading'               => 'fade-right',
							'anim_text'                  => 'fade-right',
							'anim_btn'                   => 'fade-up',
							'anim_heading_delay'         => 0,
							'anim_text_delay'            => 150,
							'anim_btn_delay'             => 300,
							'btn_text'                   => 'Read More →',
							'btn_url'                    => array( 'url' => '#' ),
							'content_align'              => 'left',
							'content_vertical'           => 'middle',
							'content_box_enable'         => 'yes',
							'content_max_width'          => array( 'size' => 520, 'unit' => 'px' ),
							'cinematic_effect'           => '',
						),
						array(
							'media_type'                 => 'image',
							'bg_image'                   => array( 'url' => 'https://picsum.photos/seed/scroll3/1920/1080' ),
							'image_effect'               => 'zoom',
							'overlay_type'               => 'gradient',
							'overlay_gradient_start'     => 'rgba(0,0,0,0.7)',
							'overlay_gradient_end'       => 'rgba(0,0,0,0.15)',
							'overlay_gradient_direction' => 'to top',
							'heading'                    => 'The Final Chapter',
							'heading_tag'                => 'h2',
							'description'                => 'The end of the scroll is just the beginning.',
							'anim_heading'               => 'zoom-in',
							'anim_text'                  => 'fade-up',
							'anim_btn'                   => 'fade-up',
							'anim_heading_delay'         => 0,
							'anim_text_delay'            => 180,
							'anim_btn_delay'             => 320,
							'btn_text'                   => 'Begin Your Journey →',
							'btn_url'                    => array( 'url' => '#' ),
							'content_align'              => 'left',
							'content_vertical'           => 'middle',
							'content_box_enable'         => 'yes',
							'content_max_width'          => array( 'size' => 520, 'unit' => 'px' ),
							'cinematic_effect'           => 'yes',
						),
					),
				),
			),

		);
	}
}

GSM_Slider_Templates::get_instance();